import {
  Award,
  Banknote,
  BarChart3,
  Briefcase,
  Building2,
  Calculator,
  CheckCircle2,
  Compass,
  Cog,
  ConciergeBell,
  Cpu,
  FileText,
  FolderCheck,
  GraduationCap,
  Home,
  LifeBuoy,
  Mail,
  MapPin,
  Megaphone,
  MessagesSquare,
  PenLine,
  Phone,
  Plane,
  Ruler,
  Scale,
  Sparkles,
  Stamp,
  Stethoscope,
  UserCheck,
  Users,
  type LucideIcon,
} from "lucide-react";

export const iconMap: Record<string, LucideIcon> = {
  award: Award,
  banknote: Banknote,
  briefcase: Briefcase,
  building: Building2,
  calculator: Calculator,
  chartBar: BarChart3,
  check: CheckCircle2,
  compass: Compass,
  concierge: ConciergeBell,
  cog: Cog,
  cpu: Cpu,
  fileText: FileText,
  folderCheck: FolderCheck,
  graduation: GraduationCap,
  home: Home,
  lifeBuoy: LifeBuoy,
  mail: Mail,
  mapPin: MapPin,
  megaphone: Megaphone,
  messages: MessagesSquare,
  penLine: PenLine,
  phone: Phone,
  plane: Plane,
  ruler: Ruler,
  scale: Scale,
  sparkles: Sparkles,
  stamp: Stamp,
  stethoscope: Stethoscope,
  userCheck: UserCheck,
  users: Users,
};

export function Icon({ name, className }: { name: string; className?: string }) {
  const Cmp = iconMap[name] ?? Sparkles;
  return <Cmp className={className} aria-hidden="true" />;
}
